INSERT INTO MEMBER (ID, USERNAME, PASSWORD) VALUES (1, 'admin@ya2do.io', 'secret');
INSERT INTO MEMBER (ID, USERNAME, PASSWORD) VALUES (2, 'marten@ya2do.io', 'user');
INSERT INTO MEMBER (ID, USERNAME, PASSWORD) VALUES (3, 'jdoe@does.net', 'unknown');

INSERT INTO MEMBER_ROLE (MEMBER_ID, ROLE) VALUES(2, 'USER');
INSERT INTO MEMBER_ROLE (MEMBER_ID, ROLE) VALUES(3, 'USER');

INSERT INTO MEMBER_ROLE (MEMBER_ID, ROLE) VALUES(1, 'USER');
INSERT INTO MEMBER_ROLE (MEMBER_ID, ROLE) VALUES(1, 'ADMIN');

